// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anephwagdyyxdipdtvbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuZXBod2FnZHl5eGRpcGR0dmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MjMyMjcsImV4cCI6MjA2NTA5OTIyN30.N08LpYLdboiNPI0lMHRfGKE7t7VOqHk0H3R4oXUd8PA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);